# Generated by Django 3.1.2 on 2020-11-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreColeccion', models.CharField(max_length=35)),
                ('primeraPublicacion', models.DateField()),
                ('estado', models.CharField(choices=[('FIN', 'Finalizado'), ('ENCURSO', 'En publicación'), ('PROX', 'No ha salido aún')], max_length=40)),
                ('autores', models.ManyToManyField(to='appLibreria.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComic', models.CharField(max_length=35)),
                ('numPaginas', models.IntegerField()),
                ('autor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appLibreria.coleccion')),
            ],
        ),
        migrations.AddField(
            model_name='coleccion',
            name='tags',
            field=models.ManyToManyField(to='appLibreria.Tag'),
        ),
    ]
